# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormRecordAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=50)),
                ('record_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormRecordReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
        migrations.AddField(
            model_name='formtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enki.Project'),
        ),
        migrations.AddField(
            model_name='formrecordattribute',
            name='form_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enki.FormType'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_record_attribute',
            field=models.ManyToManyField(to='enki.FormRecordAttribute'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enki.FormType'),
        ),
    ]
