# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0003_auto_20170217_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formrecordattributevalue',
            old_name='form_type',
            new_name='record_attribute_type',
        ),
    ]
